### ISSUE TITLE
How to implement `Creatable` with a model that has non-nullable fields

### ISSUE THREAD

**Issue by bertramakers** [tobyzerner/json-api-server#68]
Hi,

I'm trying to set up this library to work with our custom database models, and I'm having some difficulty implementing the `Creatable` interface on the respective Resource classes of our database models.

Let's say that I have a model class that looks like this (simplified):

```
final class Post
{
    public function __construct(
        public ?int $id, // Nullable so that new instances can be created to save in the DB later
        public string $title,
    ) {}
}
```

As you can see, we always require the `Post` objects to have a string title, because there is no use-case for having a post with `null` as title.

I have then created a Resource class for this model, like so:
```
use Tobyz\JsonApiServer\Field;

class PostsResource extends Resource
{
    // ...

    public function fields(): array
    {
        return [
            Field\Str::make('title')->writable()->required(),
        ];
    }
}
```

The issue occurs when I try to implement the `Creatable` interface on this class. Per the documentation, the JSON:API "create" endpoint will:

1. Call the `newModel` method to get a new model instance.
2. Deserialize and validate field data.
3. Call the `setValue` method for each field.
4. Call the create method to persist the model to storage.
5. Call the `saveValue` method for each field.

If I understand correctly, the `newModel` should instantiate a new `Post` object, but without setting any values on properties because the fields are not deserialized yet?

So I'd have to implement it like this:
```
class PostsResource extends Resource
{
    // ...

    public function newModel(): Post
    {
        return new Post();
    }
}
```

However this obviously won't work since our `Post` class requires a `title` string value.

I _could_ set an empty string as a temporary value of course, but then I'd have to set default values for basically every other required property as well which is probably going to become confusing / cumbersome.

The only other solution that I can find is using some kind of intermediate object instead of working with the `Post` class directly, for example making `newModel()` return a simple `stdClass` and converting it to an actual `Post` object in the `create()` method before saving it to the DB. But that also feels like a hack-ish workaround.

Am I maybe overlooking something in the documentation? Is there perhaps a better solution available?

Thanks for the help!

**Comment by tobyzerner** [comment]
Tricky one!

It sounds like you've understood everything correctly. The reason that creation is split into these steps is 1) for consistency with the way Updatable works and 2) to allow each field to define a setter/saver to override the resource's default implementations.

An alternative I considered was just to have a single `create` method and pass all the deserialized/validated data into that, but the drawback is that then all individual Resource implementations would then have to take responsibility for looping through fields, calling their setters, persisting the model, and then calling field savers. The interface is broken up just to take that boilerplate out of the implementation.

My first thought would be to go with your idea of an intermediate object. I don't think it's necessarily hacky. When talking about a "model" in the context of Creatable, you could think of it as internal to your Resource implementation, rather than necessarily using your application's "models". Something like a `PostBuilder`. And then actually building the `Post` model is part of the "persist the model to storage" step.

However, now the problem would be that your models for Creatable and Updatable would be different - `PostBuilder` for Creatable and an actual `Post` for Updatable - so field setters/savers would be receiving a different type depending on if it's a create or update request. I guess your options here would be either to ensure that both of these objects follow a similar contract so there is no functional difference, or to also wrap the `Post` models coming from `Findable` in a similar kind of intermediate object.

So there's no silver bullet I can think of - it's a complexity introduced by the desire to increase flexibility and allow fields to override default setting/saving behaviour. Open to suggestions if you have any!

**Comment by bertramakers** [comment]
Thanks for the detailed explanation why you went with this approach @tobyzerner ! 👌  I agree that there is no perfect solution possible. I ended up using a simple `stdClass` intermediate object, and I made sure that my `find()` implementation converts the app's model to a `stdClass` with the same structure. So the Resource class just uses a simple object without any predefined properties, and the `create` and `update` methods convert it to one of the app's models before passing it on to a repository class that saves it. This solution is the least effort for us, compared to actual Builder classes that we'd need to create for every resource / model.
